### ISSUE TITLE
[1.16] Hardened Dirt does not break with shovel

### ISSUE THREAD

**Issue by kwpugh** [Lemonszz/gubbins#4]
Hi,

I noticed on my server that Hardened Dirt spawns in worldgen, which is nice, but the block is a bit confusing.  Looks like dirt, but cannot be broken with shovels.  It seems to need a pickaxe.

Looking in your source code:

public static final Block HARDENED_DIRT = new GubbinsBlock(settings(Material.STONE, 1.0F).sounds(BlockSoundGroup.GRAVEL).

Vanilla code for dirt is:
 DIRT = register("dirt", new Block(AbstractBlock.Settings.of(Material.SOIL, MaterialColor.DIRT).strength(0.5F).sounds(BlockSoundGroup.GRAVEL)));

Would you consider changing the Hardened Dirt to be broken by a shovel?

Thank you for considering.

Regards.

**Comment by Lemonszz** [comment]
IIRC this was intentional, but I do agree with you it's confusing.
It would be cool to make it break with both a pick and shovel, but if that's not possible, I'll change it to the shovel 👍

**Comment by Lemonszz** [comment]
Fixed for 1.1.0
