### ISSUE TITLE
Crash with thrown potions

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Lemonszz/gubbins#7]
I started getting crashes after getting close to a witch. After the first crash, the game crashed while loading the world. Disabling the splash concrete powder with water feature prevents the crash.
[2020-08-01-6.log](https://github.com/Lemonszz/gubbins/files/5011527/2020-08-01-6.log)
[crash-2020-08-01_12.57.22-server.txt](https://github.com/Lemonszz/gubbins/files/5011529/crash-2020-08-01_12.57.22-server.txt)

**Comment by Lemonszz** [comment]
It looks like you're on version 1.1.0, this was fixed in 1.1.1.

Please update and if it still happens let me know!

Thanks
